### ISSUE TITLE
Mac Build

### ISSUE THREAD

**Issue by circadiansound** [jensschulze/GoodSheperd#1]
[GoodSheperd-1.0.0-mac.zip](https://github.com/jensschulze/GoodSheperd/files/3484603/GoodSheperd-1.0.0-mac.zip)

**Comment by jensschulze** [comment]
Thanks, I appreciate that you built a release! Unfortunately it is already outdated because I had some spare time to break things here … **but** thanks to your effort I decided to finally [submit my plugin to the official VCV Rack plugin library](https://github.com/VCVRack/library/issues/585), and it is already accepted. As soon as they make a new build it will be available via https://vcvrack.com/plugins.html
