### ISSUE TITLE
scale probabilities in seq-3st

### ISSUE THREAD

**Issue by glocke01** [jensschulze/GoodSheperd#12]
My feature request is to add a way to increase/decrease the probabilities in seq-3st so that you can get an effect vaguely akin to the way Grids works (more/less notes). You can already achieve a "constant offset" by adding additional modules, but what would be cool would be a non-linear scaling akin to the transfer function of HetrickCV Shaper, which would be closer to the way Grids works. (IDK if this is true technically, but it's my observation.)

**Comment by jensschulze** [comment]
Sounds like a great idea! Shaping the knobs’ behavior is no big deal. I think the hard part will be pondering where to put the "transfer function" knob(s). I hate those real estate considerations. 😄

**Comment by jensschulze** [comment]
@glocke01 If you are able to you may check out `feat/shape-knob` and compile the plugin. Would be interesting to hear if the shape curves are useful to you.

**Comment by glocke01** [comment]
I've used git before (plenty) but am not familiar with how to use it for VCV Rack. Is there official documentation for how to add plugins from source? Do I just clone and make and then move the binaries to the VCV plugins folder?

**Comment by jensschulze** [comment]
@glocke01 There is a quite extensive documentation how to [build Rack and Rack Plugins](https://vcvrack.com/manual/Building.html) on your machine. One could say it’s "just clone and make and then move the binaries to the VCV plugins folder", but as always it depends on your experience (the *great* documentation will come in very handy here) and your setup: in order to build Rack you need to have a few dependencies on your machine. As soon as you have all set up correctly it’s indeed just a `make dist` – and then you can drag the zipped plugin into the Rack plugins folder.

In the documentation it is said
> You do not need to build Rack to build plugins if you use the Rack SDK.

tbh I have always built Rack so I can’t tell you if it is even simpler with the SDK.

The build times on my MBP mid-2015 are just a fraction of the build times stated in the documentation.

**Comment by jensschulze** [comment]
@glocke01 I don’t like the shape curves I implemented, will change to the curves mhetrick uses. So this is work in progress …

**Comment by glocke01** [comment]
awesome, thanks!!
